hdf5:
  - 2
  - 1.14.6
libnetcdf:
  - 4.10.0
  - 4.9.3
mpi:
  - mpich    # [unix]
  - msmpi    # [win]
  - impi-devel  # [win]
mkl_devel:
  - 2026  # [unix]
  - 2024  # [win]
  - 2026  # [win]
impi_devel:
  - 2021.14.1  # [win]
zip_keys:
  - - hdf5
    - libnetcdf
  - - mpi
    - mkl_devel
